############################################################
# Browser
############################################################

browser=chrome
headless=false

############################################################
# Application
############################################################

url=https://ptnrs.sce.manh.com/udc/landing
username=santhoshv
password=Ncsp@1234#

############################################################
# Waits
############################################################

implicit.wait=30
explicit.wait=30

fluent.wait=300
fluent.polling=10

############################################################
# Execution
############################################################

execution.mode=SERIAL
# or PARALLEL or SERIAL

parallel.threads=2

continue.on.failure=true

############################################################
# Cucumber
############################################################

feature.path=src/test/resources/features
glue.package=stepdefinitions

############################################################
# Run Manager
############################################################

run.manager.path=RunManager.xlsx
run.manager.sheet=RunManager

############################################################
# Reporting
############################################################

report.path=Reports

############################################################
# Email
############################################################
/*
#host - which mail server to use for sending the email
#port-Which communication port should the framework use to connect to that server
#username-Which email account is sending the report
#receipients-Which email accounts should receive the report
#password - sender account app pw
#host = smtp.office365.com (for outlook and microsoft 365)
#host = smtp.gmail.com (for gmail)

*/
email.enabled=false

mail.host=smtp.zoho.in
mail.port=587
mail.username=ncstestautomation_1@zohomail.in
#mail.password=Pphg9e3sMsWK
mail.password=Ncs@2026
mail.recipients=santhoshvenkat4626@gmail.com
mail.subject=Auto Generated Mail For Report


postmanUrl=https://ptnrs.sce.manh.com
postmanAuthUrl=https://ptnrs-auth.sce.manh.com

postmanUsername=santhoshv
postmanPassword=Ncsp@1234$

postmanClientAuthorization=Basic b21uaWNvbXBvbmVudC4xLjAuMDpiNHM4cmdUeWc1NVhZTnVu